server:
  port: 8888
  servlet:
    context-path: /test001
offcn:
  ip: 192.168.188.128
  port: 6379
userbody:
  name: 优就业
  password: 123456
  birthday: 1992.10.28
  mobile: 13802789765
  address: 北京市朝阳区
spring:
  profiles:
    active: test

